### ISSUE TITLE
这个和appframework-java的区别是啥啊

### ISSUE THREAD

**Issue by whtis** [larksuite/oapi-sdk-java#1]

**Comment by mimajiushi** [comment]
+1用得好好的，完全不知道为啥又重写了一个

**Comment by zhaoche27** [comment]
之前的SDK，都是手写的。 

新的SDK， 除了 core 模块，业务的SDK都是自动生成，这样各个业务线的SDK的代码风格就是一致的了，方便开发者使用。
老的SDK，在webhook这块与spring结合的太深，无法扩展到其他用户场景。例如：有一些开发者使用了云faas方式，难以满足。
