### ISSUE TITLE
支持下载的响应处理上，没有关闭InputStream

### ISSUE THREAD

**Issue by taoyuanping** [larksuite/oapi-sdk-java#135]
这是一个有趣的问题，在使用默认的okhhtp做为底层调用框架时，在支持下载的响应处理上，好像没有关闭InputStream，在IOs.readAll里关闭的是一个ByteArrayOutputStream，关闭一个以字节数组的流是没有任何意义的，如下图

![20240801-174527](https://github.com/user-attachments/assets/055f1e43-7197-4803-a5d8-51d9fa798de5)

诡异的是，没有关闭流似乎没有对线上造成影响，比如OOM，于是我们向上溯源发现了这段有趣的代码，如下图

![20240801-174333](https://github.com/user-attachments/assets/d29d72ac-3fa0-46cd-a951-d45530d892ae)

setSupportDownLoad好像不是我们期望的那样

**Comment by maemual** [comment]
内存泄漏问题最近也有人提过，然后排查了一下，确实会有这个风险，但是 GC 给回收掉了。
![image](https://github.com/user-attachments/assets/efe4676c-5a50-49f2-bb86-f51814ef6561)
