### ISSUE TITLE
三方审批还没有service

### ISSUE THREAD

**Issue by ukihsoroy** [larksuite/oapi-sdk-java#23]
这一块是不考虑做么，还是怎样？还有这个仓库接受pr么？

**Comment by zhaoche27** [comment]
三方审批，说的是这块吗：https://open.feishu.cn/document/ukTMukTMukTM/uAzNyYjLwcjM24CM3IjN ？

**Comment by ukihsoroy** [comment]
是的

**Comment by zhaoche27** [comment]
需要使用 原生模式，封装 request 。
