### ISSUE TITLE
关于ISV应用首次创建会话订阅问题

### ISSUE THREAD

**Issue by rainchestnut** [larksuite/oapi-sdk-java#27]
有两个问题
1.关于ISV应用上线的上线清单界面，这个首次会话订阅条件的刷新条件是什么？我曾尝试过刷新页面，但是我没有监听到任何有关于相关请求，并且我使用过不管是event_callback或者p2p_chat_create还是event_callback.p2p_chat_create，都不行我该如此测试这个订阅事件，毕竟我不可能每次测试都新建一个应用去测试首次会话创建。
1.后端服务创建机器人，使用SDK，如何才能监听到首次创建会话的事件，相关的接口文档上只有接口回调形式的监听，没有SDK形式的事件type。我曾尝试过刷新上线清单界面，但是我没有监听到任何有关于相关请求，并且我使用过不管是event_callback或者p2p_chat_create还是event_callback.p2p_chat_create，都不行，我该如何监听这一事件？

以上两个问题我无法从文档及人工客服那里寻找到答案，麻烦大佬的指导

**Comment by zhaoche27** [comment]
如何才能监听到首次创建会话的事件: https://open.feishu.cn/document/ukTMukTMukTM/uYDNxYjL2QTM24iN0EjN/bot-events

关于事件的示例代码 在 readme里有说明的。
https://github.com/larksuite/oapi-sdk-java/blob/main/spring-boot-examples/src/main/java/com/larksuite/oapi/example/EventController.java

**Comment by rainchestnut** [comment]
> 如何才能监听到首次创建会话的事件: https://open.feishu.cn/document/ukTMukTMukTM/uYDNxYjL2QTM24iN0EjN/bot-events
> 
> 关于事件的示例代码 在 readme里有说明的。
> https://github.com/larksuite/oapi-sdk-java/blob/main/spring-boot-examples/src/main/java/com/larksuite/oapi/example/EventController.java
正如您所引用的文档地址，此文档只说明了接口方式如何应用，却并没有说明sdk方式注册事件处理的类型，并且文档中并没有给出一个行之有效的测试首次会话创建的方法，无法重复性的进行此事件的测试，正如我前文所言，我不可能每次测试都新建一个应用去测试首次会话创建
其次，所给出的事件示例中，我是看过的，我曾猜测app_open 事件就是此事件的类型，但是因为我无法知道如何测试这个问题，所以我无法确定

因此我现在迫切需要的是能够重复测试首次创建会话事件及其他无法重复出现的场景消息订阅的方法，其次我无法在文档中找到明确的定义SDK形式中各种订阅类型的type

**Comment by zhaoche27** [comment]
SDK 没有明确的写每一个事件的demo，你把 app_open 换成你要监听的事件类型，应该就行，触类旁通吗。

**Comment by zhaoche27** [comment]
要敢于尝试或了解源代码，idea 本地 debug ，so easy。

**Comment by rainchestnut** [comment]
现在根本原因不是代码的问题，类型定义不明确，我可以测，可以看源代码，文档不理解，我可以试，但是这种首次打开应用的订阅，对于次数有着严格的限定，我测一遍就不行了，要想再测一遍，我需要重新创建一个应用，重新部署，然后再打开，所以有没有什么简单的方法？

**Comment by zhaoche27** [comment]
明白了，当前没有简单办法。只能如果所说的这样。首次打开应用的订阅，“首次” 表示，只会有一次。
