### ISSUE TITLE
请问能否提供下如何在application.yml中添加密钥呢

### ISSUE THREAD

**Issue by QinPan1995** [larksuite/oapi-sdk-java#28]
在application.yml中添加token后，在代码中
public static final AppSettings appSettings = Config.createInternalAppSettings("***", "***", "***", ***);如何加载呢？请问，能否提供下案例

**Comment by zhaoche27** [comment]
@value  注解到一个变量， 然后  Config.createInternalAppSettings("", "", "***", ***) 的参数 使用这个@value的变量。 具体 @value 怎么使用，可以百度一下哈。https://blog.csdn.net/qq_37866486/article/details/90700996

**Comment by QinPan1995** [comment]
不能呢  Config.createInternalAppSettings是启动就会加载密钥，这个时候还未读区配置文件里面的数据呢
![image](https://user-images.githubusercontent.com/34876129/128468880-bec10a3c-2ca1-4d8c-9fba-2d83f25dd55c.png)

**Comment by zhaoche27** [comment]
https://www.cnblogs.com/fnlingnzb-learner/p/10758848.html  看看这个 @PostConstruct

**Comment by QinPan1995** [comment]
太感谢你了
