### ISSUE TITLE
关于构建请求（Request),参数 httpPath：API路径（`open-apis/`之后的路径）,审批相关的都用不了

### ISSUE THREAD

**Issue by joluzhu96** [larksuite/oapi-sdk-java#30]
审批相关的接口都是以https://www.feishu.cn/approval/openapi 开头的 导致无法构建请求

**Comment by zhaoche27** [comment]
新版的包，已经支持了，path 可以直接是：https://www.feishu.cn/approval/openapi/xxxxxx
