### ISSUE TITLE
Request.newRequest() obtain internal tenant access token，failure information

### ISSUE THREAD

**Issue by samlaiGit** [larksuite/oapi-sdk-java#33]
用Request.newRequest() 构建请求在公网服务上会出现异常，当在本地无异常
`AccessTokenObtainException: obtain internal tenant access token，failure information:http status code:200,response:{code=10003, msg='invalid param', error=null, data=omit...},`请问如何解决

**Comment by samlaiGit** [comment]
@zhaoche27 @CamelQu @chyroc @keeperlibofan 麻烦各位大佬敲敲，包的版本是1.0.17-rc5

**Comment by zhaoche27** [comment]
你的  "AppID", "AppSecret"  填写的不对或者应用没有发布

**Comment by samlaiGit** [comment]
> 你的 "AppID", "AppSecret" 填写的不对或者应用没有发布

但是我在本地调试是ok的呀

**Comment by zhaoche27** [comment]
那你需要看看具体的使用环境是不是配置没有读取到

**Comment by samlaiGit** [comment]
已解决，自己环境问题
