### ISSUE TITLE
审批事件sdk添加

### ISSUE THREAD

**Issue by zd125735** [larksuite/oapi-sdk-java#34]
https://open.feishu.cn/document/ukTMukTMukTM/uUTNxYjL1UTM24SN1EjN
审批事件的监听大概什么时候有哦？

**Comment by zhaoche27** [comment]
当前没有哈，需要你使用原生的方式（readme文档有相关说明）来处理哈

**Comment by zd125735** [comment]
在当前sdk的模式增加不能实现吗？使用原生模式，等于参数拦截解密那些都得再做一遍咯。

**Comment by lgp547** [comment]
主要是审批相关推送事件类型没拆开，都是1.0的event_callback，还得循环判断。。。

**Comment by zhaoche27** [comment]
> 在当前sdk的模式增加不能实现吗？使用原生模式，等于参数拦截解密那些都得再做一遍咯。

等于参数拦截解密那些都得再做一遍咯， 不用呀，只是事件的数据是map结构而已。
例如处理： app_open 事件（你看看 readme 文档）

 Event.setTypeHandler(this.getConfig(), "app_open", new DefaultHandler() {
            @Override
            public void Handle(Context context, Map<String, Object> event) throws Exception {
                // Print the request ID of the request
                log.info("requestId:{}", context.getRequestID());
                // Print event
                log.info("event:{}", event);
            }
        });

**Comment by zhaoche27** [comment]
> 主要是审批相关推送事件类型没拆开，都是1.0的event_callback，还得循环判断。。。

事件里不是有 type 字段，我理解是拆开的，还有 循环判断 是啥意思？

**Comment by lgp547** [comment]
> > 主要是审理相关事件类型没拆开，都是1.0的event_callback，得循环判断。。。
> 
> 事件里有类型的字段，我理解是拆开的，还有循环判断是啥英文？

sorry，是我搞错了，一开始没注意到。审批sdk搞搞呗，api还是挺多的

**Comment by zhaoche27** [comment]
@lgp547 没有问题了，close 一下哈
