### ISSUE TITLE
有考虑兼容旧的SDK吗

### ISSUE THREAD

**Issue by mimajiushi** [larksuite/oapi-sdk-java#4]
旧的SDK突然废弃，不考虑用户迁移成本？

**Comment by yuanhaoliang** [comment]
https://github.com/larksuite/oapi-sdk-java/issues/1#issuecomment-800044160

看这个吧。。。看上去是不会兼容旧的了。

**Comment by L-A-G-A** [comment]
`    private static final String APP_ID = "xxxxxxxxxxxx";

    private static final String APP_SECRET = "xxxxxxxxxxxxxxxx";

    private static final AppSettings appSettings = Config.createInternalAppSettings(APP_ID,APP_SECRET,"000000000","00000");

    private static IStore store;

    public static Config getConfig(String domain)  {

        //redis存储方法
        RedisStore redisStore = saveRedis(domain, appSettings.toString());
        return new Config( domain,  appSettings,  redisStore);

    }`

    private static final Config config = Configs.getConfig("https://open.feishu.cn");

    public static void main(String[] args) throws Exception {
        testAccessToken();
        //testFreshAccessToken();
        //testUserInfo();
    }

    private static void testAccessToken() throws Exception {
        AuthenService service = new AuthenService(config);
        AuthenAccessTokenReqBody body = new AuthenAccessTokenReqBody();
        body.setGrantType("authorization_code");
        body.setCode("X1ijpLtwMERez2s3vQTQgh");
        AuthenService.AuthenAccessTokenReqCall reqCall = service.getAuthens().accessToken(body);
        Response<UserAccessTokenInfo> response = reqCall.execute();
        System.out.println(Jsons.DEFAULT_GSON.toJson(response));
        System.out.println(Jsons.DEFAULT_GSON.toJson(response.getData()));
        System.out.println(response.getRequestID());
    }

#################################################################################

输出结果：
10:31:08.778 [main] DEBUG com.larksuite.oapi.core.api.handler.subhandler.BuildSubHandler - [build]request:POST /open-apis/authen/v1/access_token app_access_token, body:{"grant_type":"authorization_code","code":"X1ijpLtwMERez2s3vQTQgh"}
Exception in thread "main" java.lang.NullPointerException
	at com.larksuite.oapi.core.api.handler.Handler.complement(Handler.java:75)
	at com.larksuite.oapi.core.api.handler.Handler.handle(Handler.java:56)
	at com.larksuite.oapi.core.api.Api.send(Api.java:14)
	at com.larksuite.oapi.service.authen.v1.AuthenService$AuthenAccessTokenReqCall.execute(AuthenService.java:130)
	at czy.com.dldl.feishu.AuthenSample.testAccessToken(AuthenSample.java:40)
	at czy.com.dldl.feishu.AuthenSample.main(AuthenSample.java:29)

Process finished with exit code 1


请问到底是什么null错误？，

createInternalAppSettings(String appID, String appSecret, String verificationToken, String encryptKey)
里面的verificationToken和encryptKey可以填null吧？

**Comment by zhaoche27** [comment]
这个问题，已经回答过了。 [#1]
