### ISSUE TITLE
如何优雅的获取租户TOKEN

### ISSUE THREAD

**Issue by cn-luyang** [larksuite/oapi-sdk-java#40]

**Comment by zhaoche27** [comment]
在请求业务API的时候，内部已经封装管理了AccessToken的有效性了，你们为啥还需要单独获取AccessToken呢？至于 每一个API请求都需要 new Context()，是因为请求与响应中有些内容需要通过context获取（例如：request_id \ http header 等）。

**Comment by cn-luyang** [comment]
如果我需要获取当前租户TOKEN 是用什么方法，可以麻烦演示下嘛

**Comment by zhaoche27** [comment]
你可以看看源代码，你会发现 获取 租户TOKEN  使用的 “原生”的方式（README文档中有说明） 访问 api。

**Comment by cn-luyang** [comment]
`InternalAccessTokenReq internalAccessTokenReq = new InternalAccessTokenReq();
        internalAccessTokenReq.setAppId(config.getAppSettings().getAppID());
        internalAccessTokenReq.setAppSecret(config.getAppSettings().getAppSecret());
        Request<InternalAccessTokenReq, AppAccessToken> request = Request.newRequestByAuth(Constants.APP_ACCESS_TOKEN_INTERNAL_URL_PATH,
                "POST", internalAccessTokenReq, appAccessToken);
        Handler.DEFAULT.handle(ctx, request);`
说的是这一段嘛。。。 不太确定

**Comment by cn-luyang** [comment]
![image](https://user-images.githubusercontent.com/48717854/145064881-53641b53-62cb-4662-b1c7-4ef59840ff51.png)
![image](https://user-images.githubusercontent.com/48717854/145065027-fdf56282-5c19-4f31-9817-3e1dbe1a13fb.png)
在这里维护的哇，找了我半天
