### ISSUE TITLE
accessToken获取失败

### ISSUE THREAD

**Issue by L-A-G-A** [larksuite/oapi-sdk-java#5]
`` private static final String APP_ID = "xxxxxxxxxxxx";

private static final String APP_SECRET = "xxxxxxxxxxxxxxxx";
private static final String verificationToken = "xxxxxxxxxxxxxxxx";
private static final String encryptKey = "xxxxxxxxxxxxxxxx";

private static final AppSettings appSettings = Config.createInternalAppSettings(APP_ID,APP_SECRET,verificationToken,encryptKey);

public static Config getConfig(String domain)  {

    //redis存储方法
    RedisStore redisStore = saveRedis(domain, appSettings.toString());
    return new Config( domain,  appSettings,  redisStore);

}`
##########################################################

private static final Config config = Configs.getConfig("https://open.feishu.cn");

public static void main(String[] args) throws Exception {
    testAccessToken();
    //testFreshAccessToken();
    //testUserInfo();
}

private static void testAccessToken() throws Exception {
    AuthenService service = new AuthenService(config);
    AuthenAccessTokenReqBody body = new AuthenAccessTokenReqBody();
    body.setGrantType("authorization_code");
    body.setCode("X1ijpLtwMERez2s3vQTQgh");
    AuthenService.AuthenAccessTokenReqCall reqCall = service.getAuthens().accessToken(body);
    Response<UserAccessTokenInfo> response = reqCall.execute();
    System.out.println(Jsons.DEFAULT_GSON.toJson(response));
    System.out.println(Jsons.DEFAULT_GSON.toJson(response.getData()));
    System.out.println(response.getRequestID());
}
#################################################################################

输出结果：
10:xxx:xxx.xxx [main] DEBUG com.larksuite.oapi.core.api.handler.subhandler.BuildSubHandler - [build]request:POST /open-apis/authen/v1/access_token app_access_token, body:{"grant_type":"authorization_code","code":"X1ijpLtwMERez2s3vQTQgh"}
Exception in thread "main" java.lang.NullPointerException
at com.larksuite.oapi.core.api.handler.Handler.complement(Handler.java:75)
at com.larksuite.oapi.core.api.handler.Handler.handle(Handler.java:56)
at com.larksuite.oapi.core.api.Api.send(Api.java:14)
at com.larksuite.oapi.service.authen.v1.AuthenService$AuthenAccessTokenReqCall.execute(AuthenService.java:130)
at czy.com.dldl.feishu.AuthenSample.testAccessToken(AuthenSample.java:40)
at czy.com.dldl.feishu.AuthenSample.main(AuthenSample.java:29)

Process finished with exit code 1

请问到底是什么null错误？

**Comment by zhaoche27** [comment]
我测试了一下，没有问题。

saveRedis 怎么写的？
RedisStore redisStore = saveRedis(domain, appSettings.toString());

**Comment by L-A-G-A** [comment]
> 我测试了一下，没有问题。
> 
> saveRedis 怎么写的？
> RedisStore redisStore = saveRedis(domain, appSettings.toString());

 public static RedisStore saveRedis(String key,String value) {
        RedisStore redisStore = new RedisStore();
        try {
            redisStore.put(key,value,120,TimeUnit.MINUTES);
        }catch (Exception e){
            e.printStackTrace();
        }
        return redisStore;
    }


可以加下飞书好友么？飞书java开发的太少了，网上也找不到什么好的文档，天天摸黑

**Comment by zhaoche27** [comment]
可以的，我的二维码：
![image](https://user-images.githubusercontent.com/5029131/111937976-ecdcfb00-8b03-11eb-99c6-bdfd52f2a38c.png)

**Comment by zhaoche27** [comment]
![image](https://user-images.githubusercontent.com/5029131/111951596-d8f2c280-8b1e-11eb-8ab4-2c50256d5871.png)

增加 kotlin-stdlib jar
<dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib</artifactId>
            <version>1.4.31</version>
            <scope>compile</scope>
        </dependency>
