### ISSUE TITLE
富文本标题设置不生效

### ISSUE THREAD

**Issue by neversoft-club** [larksuite/oapi-sdk-java#64]
public class MessagePostContent {

  @SerializedName("text")
  private String title;
  @SerializedName("content")
  private MessagePostElement[][] content;

title这里设置成了text，没有标题样式了

**Comment by zhailuxubyte** [comment]
> public class MessagePostContent {
> 
> @SerializedName("text") private String title; @SerializedName("content") private MessagePostElement[][] content;
> 
> title这里设置成了text，没有标题样式了

<img width="172" alt="image" src="https://user-images.githubusercontent.com/106234500/190380881-4f720e49-28ae-424f-a3c2-65861ce7615c.png"> 欢迎加群讨论哈

最新版已经修改哈：https://mvnrepository.com/artifact/com.larksuite.oapi/oapi-sdk/2.0.2-rc5

**Comment by zhailuxubyte** [comment]
已解决
