### ISSUE TITLE
新版SDK的一个疑问

### ISSUE THREAD

**Issue by lanshiqin** [larksuite/oapi-sdk-java#9]
目前的service下业务包命名带版本号v3、v4这样的。如果后期业务版本升级是否会出现更多带v的版本号。
最终提供给开发者的SDK是否会存在同个业务的不同版本号，使用时可能产生不确定性。
是否考虑使用不同的git分支来维护不同系列的版本号，像Spring那样？

**Comment by zhaoche27** [comment]
我们当时也想这样做来着，考虑到我们有许多的业务线（例如：IM、通讯录），如果一个业务线一个包，用户使用起来会麻烦一些，因为用户的一个项目可能会涉及到许多的业务线。 其次各个业务线的发展不一致，所以有些是v3 ，有些是v4。
